name:                lq-games
version:             0.1.0.0
github:              "githubuser/lq-games"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2024 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/lq-games#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- hmatrix >= 0.20.2
- ad >= 4.5.6
- vector >= 0.13.1.0
- linear
- split
- diagrams-lib
- diagrams-cairo
- filepath
- directory
- process

ghc-options:
- -O2
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wno-orphans
- -Wno-partial-fields
- -Wno-incomplete-uni-patterns
- -Wno-incomplete-patterns
- -Wno-unrecognised-pragmas

default-extensions:
  - DeriveAnyClass
  - StandaloneDeriving
  - DeriveGeneric
  - RankNTypes
  - ImpredicativeTypes
  - NoMonomorphismRestriction
  - FlexibleContexts
  - TypeFamilies

library:
  source-dirs: src



executables:
  lq-games-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lq-games
  example1:
    main:                Main.hs
    source-dirs:         examples/Example1
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lq-games
  example2:
    main:                Main.hs
    source-dirs:         examples/Example2
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lq-games
  example3:
    main: Main.hs
    source-dirs: examples/Example3
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lq-games
  example4:
    main: Main.hs
    source-dirs: examples/Example4
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lq-games
  benchmark:
    main: Benchmark.hs
    source-dirs: bench
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - criterion
    - lq-games
    - deepseq

tests:
  lq-games-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
    - hspec-contrib
    - HUnit
    - QuickCheck
    - lq-games
